// Generated by Circuit Convert. Combine names that another imported module also declares:
// Foundation's re-exported Combine on a Mac simulating Windows (-DCIRCUIT_WINDOWS_SIM), SwiftCrossUI's
// own ObservableObject / Published / Publisher / Cancellable wherever it stands in for SwiftUI.
// The app's code means Combine's, so OpenCombine's names win. Elsewhere this file is empty.
#if canImport(OpenCombine) && (CIRCUIT_WINDOWS_SIM || (canImport(SwiftCrossUI) && !canImport(SwiftUI)))
import OpenCombine
typealias Published = OpenCombine.Published
typealias ObservableObject = OpenCombine.ObservableObject
typealias ObservableObjectPublisher = OpenCombine.ObservableObjectPublisher
typealias AnyCancellable = OpenCombine.AnyCancellable
typealias Cancellable = OpenCombine.Cancellable
typealias AnyPublisher = OpenCombine.AnyPublisher
typealias Publisher = OpenCombine.Publisher
typealias Publishers = OpenCombine.Publishers
typealias Subscriber = OpenCombine.Subscriber
typealias Subscribers = OpenCombine.Subscribers
typealias Subscription = OpenCombine.Subscription
typealias Subscriptions = OpenCombine.Subscriptions
typealias Subject = OpenCombine.Subject
typealias PassthroughSubject = OpenCombine.PassthroughSubject
typealias CurrentValueSubject = OpenCombine.CurrentValueSubject
typealias Just = OpenCombine.Just
typealias Future = OpenCombine.Future
typealias Deferred = OpenCombine.Deferred
typealias Empty = OpenCombine.Empty
typealias Fail = OpenCombine.Fail
typealias Record = OpenCombine.Record
typealias Scheduler = OpenCombine.Scheduler
typealias ImmediateScheduler = OpenCombine.ImmediateScheduler
typealias ConnectablePublisher = OpenCombine.ConnectablePublisher
typealias CombineIdentifier = OpenCombine.CombineIdentifier
typealias CustomCombineIdentifierConvertible = OpenCombine.CustomCombineIdentifierConvertible
typealias TopLevelDecoder = OpenCombine.TopLevelDecoder
typealias TopLevelEncoder = OpenCombine.TopLevelEncoder
typealias AnySubscriber = OpenCombine.AnySubscriber
#endif
