// swift-tools-version: 5.9
// Generated by Circuit Convert. Builds the converted sources for Windows, Linux and macOS.
// Simulate the Windows configuration on a Mac:  swift build -Xswiftc -DCIRCUIT_WINDOWS_SIM
import PackageDescription

let package = Package(
    name: "UIProbeCore",
    platforms: [.macOS("15.0")],
    products: [.library(name: "UIProbeCore", targets: ["UIProbeCore"])],
    dependencies: [
        .package(url: "https://github.com/moreSwift/swift-cross-ui.git", .upToNextMinor(from: "0.9.0")),
        .package(url: "https://github.com/OpenCombine/OpenCombine.git", from: "0.14.0"),
    ],
    targets: [
        .target(
            name: "CircuitPortKit",
            dependencies: [
                .product(name: "SwiftCrossUI", package: "swift-cross-ui"),
                .product(name: "OpenCombine", package: "OpenCombine"),
                .product(name: "OpenCombineFoundation", package: "OpenCombine"),
                .product(name: "OpenCombineDispatch", package: "OpenCombine"),
            ],
            path: "kit/CircuitPortKit"
        ),
        .target(
            name: "UIProbeCore",
            dependencies: [
                "CircuitPortKit",
                .product(name: "SwiftCrossUI", package: "swift-cross-ui"),
                .product(name: "OpenCombine", package: "OpenCombine"),
                .product(name: "OpenCombineFoundation", package: "OpenCombine"),
                .product(name: "OpenCombineDispatch", package: "OpenCombine"),
            ],
            path: "app",
            sources: [
                "Sources/Counter.swift",
                "Sources/Symbols.swift",
                "_CircuitConvert/CombineNamesForSimulation.swift",
            ]
        ),
    ]
)
