// Generated by Circuit Convert. Only active when a Mac simulates the Windows configuration
// (-DCIRCUIT_WINDOWS_SIM): Foundation re-exports Combine there, so its names would be ambiguous with
// OpenCombine's. Windows and Linux have no Combine; this file compiles to nothing on them.
#if CIRCUIT_WINDOWS_SIM && canImport(OpenCombine)
import OpenCombine
typealias Published = OpenCombine.Published
typealias ObservableObject = OpenCombine.ObservableObject
typealias ObservableObjectPublisher = OpenCombine.ObservableObjectPublisher
typealias AnyCancellable = OpenCombine.AnyCancellable
typealias Cancellable = OpenCombine.Cancellable
typealias AnyPublisher = OpenCombine.AnyPublisher
typealias Publisher = OpenCombine.Publisher
typealias Publishers = OpenCombine.Publishers
typealias Subscriber = OpenCombine.Subscriber
typealias Subscribers = OpenCombine.Subscribers
typealias Subscription = OpenCombine.Subscription
typealias Subscriptions = OpenCombine.Subscriptions
typealias Subject = OpenCombine.Subject
typealias PassthroughSubject = OpenCombine.PassthroughSubject
typealias CurrentValueSubject = OpenCombine.CurrentValueSubject
typealias Just = OpenCombine.Just
typealias Future = OpenCombine.Future
typealias Deferred = OpenCombine.Deferred
typealias Empty = OpenCombine.Empty
typealias Fail = OpenCombine.Fail
typealias Record = OpenCombine.Record
typealias Scheduler = OpenCombine.Scheduler
typealias ImmediateScheduler = OpenCombine.ImmediateScheduler
typealias ConnectablePublisher = OpenCombine.ConnectablePublisher
typealias CombineIdentifier = OpenCombine.CombineIdentifier
typealias CustomCombineIdentifierConvertible = OpenCombine.CustomCombineIdentifierConvertible
typealias TopLevelDecoder = OpenCombine.TopLevelDecoder
typealias TopLevelEncoder = OpenCombine.TopLevelEncoder
typealias AnySubscriber = OpenCombine.AnySubscriber
#endif
