// GENERATED by tools/support-agent/install.mjs from sites.mjs — do not edit.
export const TERMS = ["black label","blacklabel","blvigil","vigil","homefront","blbestate","blb estate","bl bestate","blacklabelbots","asgolfclothing","asgolf","as golf","gcwars","gulf coast","blackwater"];
