// swift-tools-version: 5.9
// Generated by Circuit Convert. Builds the converted sources for Windows, Linux and macOS.
// Simulate the Windows configuration on a Mac:  swift build -Xswiftc -DCIRCUIT_WINDOWS_SIM
import PackageDescription

let package = Package(
    name: "BlackLabelAcademyCore",
    platforms: [.macOS("15.0")],
    products: [.library(name: "BlackLabelAcademyCore", targets: ["BlackLabelAcademyCore"])],
    dependencies: [
        .package(url: "https://github.com/OpenCombine/OpenCombine.git", from: "0.14.0"),
        .package(url: "https://github.com/swiftlang/swift-toolchain-sqlite.git", from: "1.0.0"),
    ],
    targets: [
        .target(
            name: "CircuitPortKit",
            dependencies: [
                .product(name: "OpenCombine", package: "OpenCombine"),
                .product(name: "OpenCombineFoundation", package: "OpenCombine"),
                .product(name: "OpenCombineDispatch", package: "OpenCombine"),
            ],
            path: "kit/CircuitPortKit"
        ),
        .target(
            name: "BlackLabelAcademyCore",
            dependencies: [
                "CircuitPortKit",
                .product(name: "OpenCombine", package: "OpenCombine"),
                .product(name: "OpenCombineFoundation", package: "OpenCombine"),
                .product(name: "OpenCombineDispatch", package: "OpenCombine"),
                .product(name: "SwiftToolchainCSQLite", package: "swift-toolchain-sqlite"),
            ],
            path: "app",
            sources: [
                "Sources/App.swift",
                "Sources/Calculators.swift",
                "Sources/Certificates.swift",
                "Sources/Cohort.swift",
                "Sources/ContentDB.swift",
                "Sources/Holographic.swift",
                "Sources/Markdown.swift",
                "Sources/Model.swift",
                "Sources/Recall.swift",
                "Sources/Spotlight.swift",
                "Sources/StatClaim.swift",
                "Sources/Store.swift",
                "Sources/StudyHabit.swift",
                "Sources/StudyWidgetData.swift",
                "Sources/Theme.swift",
                "Sources/Trial.swift",
                "Sources/Tutor.swift",
                "Sources/Updater.swift",
                "Sources/UpdaterUI.swift",
                "Sources/Views.swift",
                "Sources/iOSLayout.swift",
                "_CircuitConvert/CombineNamesForSimulation.swift",
            ]
        ),
    ]
)
