// swift-tools-version: 5.9
// Generated by Circuit Convert. Builds the converted sources for Windows, Linux and macOS.
// Simulate the Windows configuration on a Mac:  swift build -Xswiftc -DCIRCUIT_WINDOWS_SIM
import PackageDescription

let package = Package(
    name: "BlackLabelTradingCore",
    platforms: [.macOS("15.0")],
    products: [.library(name: "BlackLabelTradingCore", targets: ["BlackLabelTradingCore"])],
    dependencies: [
        .package(url: "https://github.com/OpenCombine/OpenCombine.git", from: "0.14.0"),
        .package(url: "https://github.com/apple/swift-crypto.git", from: "3.0.0"),
    ],
    targets: [
        .target(
            name: "CircuitPortKit",
            dependencies: [
                .product(name: "OpenCombine", package: "OpenCombine"),
                .product(name: "OpenCombineFoundation", package: "OpenCombine"),
                .product(name: "OpenCombineDispatch", package: "OpenCombine"),
            ],
            path: "kit/CircuitPortKit"
        ),
        .target(
            name: "BlackLabelTradingCore",
            dependencies: [
                "CircuitPortKit",
                .product(name: "OpenCombine", package: "OpenCombine"),
                .product(name: "OpenCombineFoundation", package: "OpenCombine"),
                .product(name: "OpenCombineDispatch", package: "OpenCombine"),
                .product(name: "Crypto", package: "swift-crypto"),
            ],
            path: "app",
            sources: [
                "Sources/AlertsEngine.swift",
                "Sources/Analytics.swift",
                "Sources/Auth.swift",
                "Sources/Backtest.swift",
                "Sources/BacktestDepth.swift",
                "Sources/ChartRender.swift",
                "Sources/ChartScreen.swift",
                "Sources/Charting.swift",
                "Sources/EngineFireMarkers.swift",
                "Sources/FeedClient.swift",
                "Sources/FeedTypes.swift",
                "Sources/Feeds.swift",
                "Sources/HoloTheme.swift",
                "Sources/Holographic.swift",
                "Sources/JournalImport.swift",
                "Sources/LiveChart.swift",
                "Sources/Model.swift",
                "Sources/PaperTrade.swift",
                "Sources/Patterns.swift",
                "Sources/Replay.swift",
                "Sources/RuleProfile.swift",
                "Sources/Screener.swift",
                "Sources/Screens.swift",
                "Sources/Screens2.swift",
                "Sources/Screens3.swift",
                "Sources/SignalCore.swift",
                "Sources/StoreDisk.swift",
                "Sources/StrategyBuilder.swift",
                "Sources/Theme.swift",
                "Sources/ThemeStudio.swift",
                "Sources/TradeMath.swift",
                "Sources/TradingKeychain.swift",
                "Sources/TradingSessionStore.swift",
                "Sources/Updater.swift",
                "Sources/UpdaterUI.swift",
                "Sources/WatchlistModel.swift",
                "_CircuitConvert/CombineNamesForSimulation.swift",
            ]
        ),
    ]
)
