// swift-tools-version: 5.9
// Generated by Circuit Convert. Builds the converted sources for Windows, Linux and macOS.
// Simulate the Windows configuration on a Mac:  swift build -Xswiftc -DCIRCUIT_WINDOWS_SIM
import PackageDescription

let package = Package(
    name: "BlackLabelHomeCore",
    platforms: [.macOS("15.0")],
    products: [.library(name: "BlackLabelHomeCore", targets: ["BlackLabelHomeCore"])],
    dependencies: [
        .package(url: "https://github.com/OpenCombine/OpenCombine.git", from: "0.14.0"),
        .package(url: "https://github.com/swiftlang/swift-toolchain-sqlite.git", from: "1.0.0"),
    ],
    targets: [
        .target(
            name: "CircuitPortKit",
            dependencies: [
                .product(name: "OpenCombine", package: "OpenCombine"),
                .product(name: "OpenCombineFoundation", package: "OpenCombine"),
                .product(name: "OpenCombineDispatch", package: "OpenCombine"),
            ],
            path: "kit/CircuitPortKit"
        ),
        .target(
            name: "BlackLabelHomeCore",
            dependencies: [
                "CircuitPortKit",
                .product(name: "OpenCombine", package: "OpenCombine"),
                .product(name: "OpenCombineFoundation", package: "OpenCombine"),
                .product(name: "OpenCombineDispatch", package: "OpenCombine"),
                .product(name: "SwiftToolchainCSQLite", package: "swift-toolchain-sqlite"),
            ],
            path: "app",
            sources: [
                "Automation.swift",
                "AwayAlertsViews.swift",
                "CameraViews.swift",
                "Climate.swift",
                "ClimateViews.swift",
                "Discovery.swift",
                "DiscoveryCatalog.swift",
                "Energy.swift",
                "EnergyViews.swift",
                "Geofence.swift",
                "HomeCore.swift",
                "HomeDatabase.swift",
                "HomeStore.swift",
                "HomeViews.swift",
                "Homefront.swift",
                "MenuBar.swift",
                "MenuBarViews.swift",
                "SensorViews.swift",
                "Shared/BLShell.swift",
                "Updater.swift",
                "VigilHouse3DView.swift",
                "VigilHouseView.swift",
                "_CircuitConvert/CombineNamesForSimulation.swift",
            ]
        ),
    ]
)
