import Foundation
#if canImport(Darwin) && !CIRCUIT_WINDOWS_SIM
import Darwin
#elseif canImport(ucrt)
import ucrt
import WinSDK
#elseif canImport(Glibc)
import Glibc
#endif

nonisolated enum AcademicDocumentHeadlessCommand {
    static let launchFlag = "--ace-academic-document"

    static func runForever() -> Never {
        Task.detached {
            var committedDocumentPath: String?
            do {
                var input = Data()
                while let chunk = try FileHandle.standardInput.read(upToCount: 65_536), !chunk.isEmpty {
                    input.append(chunk)
                    guard input.count <= 1_000_000 else { throw AcademicDocumentError.invalid("The document request is too large.") }
                }
                let request = try JSONDecoder().decode(AcademicDocumentRequest.self, from: input)
                try AcademicDocument.validate(request)
                guard let authority = NativeHeadlessEffectAuthority.acquire() else {
                    throw AcademicDocumentError.invalid("No active owner request admitted this document writer.")
                }
                var evidence: [AcademicSourceEvidence] = []
                for source in request.sources {
                    try Task.checkCancellation()
                    try requireActive(authority)
                    evidence.append(try await AcademicSourceFetcher().fetch(source))
                }
                let quotationCount = try AcademicDocument.verify(request, evidence: evidence)
                let document = try AcademicDOCX.render(request, evidence: evidence)
                try Task.checkCancellation()
                try requireActive(authority)
                try AcademicDOCX.saveNew(document, to: request.outputPath)
                committedDocumentPath = request.outputPath
                let readback = try Data(contentsOf: URL(fileURLWithPath: request.outputPath), options: [.mappedIfSafe])
                guard readback == document else { throw AcademicDocumentError.invalid("The saved document did not match the generated bytes.") }
                let body = request.paragraphs.map { $0.map(\.text).joined() }.joined(separator: "\n")
                let digest = AcademicDocument.sha256(readback)
                try requireActive(authority)
                let detector = await AcademicDetector.check(text: body, documentSHA256: digest)
                try Task.checkCancellation()
                let detectorData = try JSONEncoder().encode(detector)
                let detectorJSON = try JSONSerialization.jsonObject(with: detectorData)
                let reviewPath = request.outputPath + ".ace-review.json"
                try requireActive(authority)
                var reviewSaved = false
                do { try AcademicDOCX.saveNew(detectorData, to: reviewPath); reviewSaved = true } catch {}
                emit(["status": "saved", "path": request.outputPath,
                      "sha256": AcademicDocument.sha256(readback), "format": "MLA 9 defaults",
                      "bodyWordCount": body.split(whereSeparator: \.isWhitespace).count,
                      "sourcesRetrieved": evidence.count, "quotationsMatched": quotationCount,
                      "citationConsistency": "checked", "detector": detectorJSON,
                      "detectorReviewPath": reviewSaved ? reviewPath : "not saved; preserve this result",
                      "reviewRequired": "Check bibliographic metadata, claim support, assignment details and final pagination. Passage matches do not establish factual accuracy.",
                      "destination": "local DOCX; no Google Docs delivery was performed"], code: 0)
            } catch {
                var result: [String: Any] = [
                    "status": committedDocumentPath == nil ? "failed" : "partial",
                    "message": (error as? AcademicDocumentError)?.localizedDescription
                        ?? "The document could not be completed. Check the input, source access and output folder."
                ]
                if let committedDocumentPath {
                    result["path"] = committedDocumentPath
                    result["reviewRequired"] = "A document was written before this interruption. Inspect it before retrying; the complete review is not verified."
                }
                emit(result, code: 3)
            }
        }
        dispatchMain()
    }

    private static func requireActive(_ authority: NativeHeadlessEffectAuthority) throws {
        guard authority.isValid() else {
            throw AcademicDocumentError.invalid("The owner request ended or Private Mode began. No further document work was performed.")
        }
    }

    private static func emit(_ object: [String: Any], code: Int32) -> Never {
        let data = (try? JSONSerialization.data(withJSONObject: object, options: [.sortedKeys])) ?? Data()
        FileHandle.standardOutput.write(data + Data("\n".utf8))
        exit(code)
    }
}
