// swift-tools-version: 5.9
// Generated by Circuit Convert. Builds the converted sources for Windows, Linux and macOS.
// Simulate the Windows configuration on a Mac:  swift build -Xswiftc -DCIRCUIT_WINDOWS_SIM
import PackageDescription

let package = Package(
    name: "Circuit_PortCheck_20260918Core",
    platforms: [.macOS("15.0")],
    products: [.library(name: "Circuit_PortCheck_20260918Core", targets: ["Circuit_PortCheck_20260918Core"])],
    dependencies: [
        .package(url: "https://github.com/apple/swift-crypto.git", from: "3.0.0"),
    ],
    targets: [
        .target(
            name: "CircuitPortKit",
            dependencies: [
            ],
            path: "kit/CircuitPortKit"
        ),
        .target(
            name: "Circuit_PortCheck_20260918Core",
            dependencies: [
                "CircuitPortKit",
                .product(name: "Crypto", package: "swift-crypto"),
            ],
            path: "app",
            sources: [
                "macos/CircuitLauncher.swift",
                "macos/CircuitUpdater.swift",
            ]
        ),
    ]
)
