#!/usr/bin/env node
// Generates CircuitPortKit/SymbolPaths.swift: the vector path of every SF Symbol name listed in
// sf-symbols-to-fluent.json, taken from Microsoft's Fluent UI System Icons (MIT), so SwiftUI's
// Image(systemName:) draws a real icon on Windows, in the view's foreground color, at any size.
//
//   node lib/convert-kit/tools/gen-symbols.mjs <fluentui-system-icons checkout>
//
// The checkout only needs assets/*/SVG/ic_fluent_*_20_{regular,filled}.svg and LICENSE (a sparse
// checkout is enough). Fails on a mapping to an icon or style that does not exist.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const repo = process.argv[2];
if (!repo || !fs.existsSync(path.join(repo, 'assets'))) {
  console.error('usage: node gen-symbols.mjs <fluentui-system-icons checkout>');
  process.exit(2);
}
const mapping = JSON.parse(fs.readFileSync(path.join(here, 'sf-symbols-to-fluent.json'), 'utf8'));
const license = fs.readFileSync(path.join(repo, 'LICENSE'), 'utf8').split('\n')[2]?.trim() ?? 'Copyright (c) Microsoft Corporation';

const snake = (name) => name.toLowerCase().replace(/[^a-z0-9]+/g, '_');
const entries = [];
const errors = [];
for (const [sf, value] of Object.entries(mapping)) {
  if (sf.startsWith('_')) continue;
  const [icon, style] = value;
  const file = path.join(repo, 'assets', icon, 'SVG', `ic_fluent_${snake(icon)}_20_${style}.svg`);
  if (!fs.existsSync(file)) { errors.push(`${sf}: no ${style} 20px SVG for "${icon}" (${path.relative(repo, file)})`); continue; }
  const svg = fs.readFileSync(file, 'utf8');
  const view = svg.match(/viewBox="([^"]+)"/)?.[1] ?? '0 0 20 20';
  if (view.trim() !== '0 0 20 20') { errors.push(`${sf}: unexpected viewBox ${view}`); continue; }
  const parts = [];
  let evenOdd = false;
  for (const el of svg.matchAll(/<(path|rect)\b([^>]*)\/?>/g)) {
    const [, tag, attrs] = el;
    const attr = (n) => attrs.match(new RegExp(`\\b${n}="([^"]*)"`))?.[1];
    if (attr('fill-rule') === 'evenodd' || attr('clip-rule') === 'evenodd') evenOdd = true;
    if (tag === 'path') {
      const d = attr('d');
      if (d) parts.push(d.trim());
    } else {
      const x = Number(attr('x') ?? 0), y = Number(attr('y') ?? 0), w = Number(attr('width')), h = Number(attr('height'));
      if (w > 0 && h > 0) parts.push(`M${x} ${y}H${x + w}V${y + h}H${x}Z`);
    }
  }
  const d = parts.join(' ');
  if (!d) { errors.push(`${sf}: no path data in ${path.relative(repo, file)}`); continue; }
  if (/[^MLHVCSQTZmlhvcsqtz0-9eE.,\s-]/.test(d)) { errors.push(`${sf}: unsupported path command in ${path.relative(repo, file)}`); continue; }
  entries.push({ sf, icon, style, d, evenOdd });
}
if (errors.length) {
  console.error(errors.join('\n'));
  process.exit(1);
}
entries.sort((a, b) => (a.sf < b.sf ? -1 : 1));
const swift = [
  '// Generated by lib/convert-kit/tools/gen-symbols.mjs — do not edit by hand.',
  '// SF Symbol name → the 20×20 vector path of its Fluent UI System Icons counterpart.',
  `// Fluent UI System Icons: https://github.com/microsoft/fluentui-system-icons — MIT License, ${license}.`,
  '#if canImport(SwiftCrossUI) && (!canImport(SwiftUI) || CIRCUIT_WINDOWS_SIM)',
  'enum CircuitSymbolPaths {',
  '    /// SVG path data in a 20×20 box (absolute M/L/H/V/C/S/Q/T/Z commands).',
  '    static let paths: [String: String] = [',
  ...entries.map((e) => `        ${JSON.stringify(e.sf)}: ${JSON.stringify(e.d)},`),
  '    ]',
  '    /// Symbols whose path is filled with the even-odd rule (the rest: nonzero).',
  `    static let evenOdd: Set<String> = [${entries.filter((e) => e.evenOdd).map((e) => JSON.stringify(e.sf)).join(', ')}]`,
  '}',
  '#endif',
  '',
].join('\n');
const out = path.join(here, '..', 'CircuitPortKit', 'SymbolPaths.swift');
fs.writeFileSync(out, swift);
console.log(`wrote ${path.relative(process.cwd(), out)}: ${entries.length} symbols (${(swift.length / 1024).toFixed(0)} KB)`);
